-- ===================================================================
-- Customer Shopping Behavior SQL Analytics Suite
-- Database Target: PostgreSQL / MySQL / SQLite / DuckDB
-- Dataset: customer_shopping_behavior.csv (3,900 records)
-- ===================================================================

-- -------------------------------------------------------------------
-- 0. Table Schema Definition & Data Import Guide
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer (
    customer_id             INT PRIMARY KEY,
    age                     INT,
    gender                  VARCHAR(20),
    item_purchased          VARCHAR(100),
    category                VARCHAR(50),
    purchase_amount         NUMERIC(10, 2),
    location                VARCHAR(100),
    size                    VARCHAR(10),
    color                   VARCHAR(50),
    season                  VARCHAR(20),
    review_rating           NUMERIC(3, 2),
    subscription_status     VARCHAR(10),
    shipping_type           VARCHAR(50),
    discount_applied        VARCHAR(10),
    promo_code_used         VARCHAR(10),
    previous_purchases      INT,
    payment_method          VARCHAR(50),
    frequency_of_purchases  VARCHAR(50)
);

-- PostgreSQL CSV Data Copy Command (Execute in psql or pgAdmin):
-- COPY customer FROM '/path/to/customer_shopping_behavior.csv' WITH (FORMAT csv, HEADER true);

-- Quick Inspection
SELECT * FROM customer LIMIT 20;


-- -------------------------------------------------------------------
-- Q1. Revenue Generated by Male & Female Customers
-- -------------------------------------------------------------------
SELECT 
    gender, 
    SUM(purchase_amount) AS revenue,
    COUNT(customer_id) AS customer_count,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
GROUP BY gender
ORDER BY revenue DESC;


-- -------------------------------------------------------------------
-- Q2. Customers Using Discounts Spending Above Average
-- -------------------------------------------------------------------
SELECT 
    customer_id, 
    purchase_amount,
    discount_applied,
    promo_code_used
FROM customer 
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;


-- -------------------------------------------------------------------
-- Q3. Top 5 Products with Highest Average Review Rating
-- -------------------------------------------------------------------
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS average_product_rating,
    COUNT(customer_id) AS total_reviews
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC, total_reviews DESC
LIMIT 5;


-- -------------------------------------------------------------------
-- Q4. Average Purchase Amount: Standard vs Express Shipping
-- -------------------------------------------------------------------
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    COUNT(customer_id) AS total_orders
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- -------------------------------------------------------------------
-- Q5. Subscriber vs Non-Subscriber Spend & Revenue Comparison
-- -------------------------------------------------------------------
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- -------------------------------------------------------------------
-- Q6. Top 5 Products by Discount Application Rate
-- -------------------------------------------------------------------
SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- -------------------------------------------------------------------
-- Q7. Customer Lifecycle Segmentation (New, Returning, Loyal)
-- -------------------------------------------------------------------
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS number_of_customers,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM customer), 2) AS percentage_of_total
FROM customer_type 
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


-- -------------------------------------------------------------------
-- Q8. Top 3 Most Purchased Products within Each Category
-- -------------------------------------------------------------------
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- -------------------------------------------------------------------
-- Q9. Subscription Status Among Frequent Repeat Buyers (>5 Previous Purchases)
-- -------------------------------------------------------------------
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers,
    ROUND(100.0 * COUNT(customer_id) / SUM(COUNT(customer_id)) OVER (), 2) AS subscriber_percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- -------------------------------------------------------------------
-- Q10. Revenue Contribution by Age Group Cohort
-- -------------------------------------------------------------------
WITH age_binned AS (
    SELECT 
        CASE 
            WHEN age <= 31 THEN 'Young Adult (18-31)'
            WHEN age BETWEEN 32 AND 44 THEN 'Adult (32-44)'
            WHEN age BETWEEN 45 AND 57 THEN 'Middle-Aged (45-57)'
            ELSE 'Senior (58+)'
        END AS age_group,
        purchase_amount
    FROM customer
)
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM age_binned
GROUP BY age_group
ORDER BY total_revenue DESC;

