const SQL_QUERIES = [
  {
    id: 1,
    title: "Q1: Revenue by Gender",
    question: "What is the revenue generated by Male & Female Customers?",
    sql: `SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;`,
    description: "Calculates total purchase revenue split by gender to identify high-value customer segments.",
    category: "Revenue Analysis"
  },
  {
    id: 2,
    title: "Q2: Discounted Purchases Above Average",
    question: "Which customers used a discount but still spent more than the average purchase amount?",
    sql: `SELECT customer_id, purchase_amount 
FROM customer 
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);`,
    description: "Identifies high-spending customers who leverage discounts, highlighting promo efficiency.",
    category: "Discount & Pricing"
  },
  {
    id: 3,
    title: "Q3: Top 5 Highest Rated Products",
    question: "Which are the top 5 products with the highest average review rating?",
    sql: `SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;`,
    description: "Ranks products by average customer satisfaction score to feature top performers.",
    category: "Product Rating"
  },
  {
    id: 4,
    title: "Q4: Shipping Spend Comparison",
    question: "Compare the average Purchase Amounts between Standard and Express Shipping.",
    sql: `SELECT shipping_type, AVG(purchase_amount) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;`,
    description: "Compares spending behavior across shipping methods to evaluate premium delivery uptake.",
    category: "Logistics"
  },
  {
    id: 5,
    title: "Q5: Subscriber vs Non-Subscriber Value",
    question: "Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.",
    sql: `SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;`,
    description: "Evaluates subscription program ROI by comparing volume, average order size, and gross revenue.",
    category: "Subscription ROI"
  },
  {
    id: 6,
    title: "Q6: Top 5 Products by Discount Rate",
    question: "Which 5 products have the highest percentage of purchases with discounts applied?",
    sql: `SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;`,
    description: "Discovers products most reliant on discount codes to analyze margin impact.",
    category: "Discount & Pricing"
  },
  {
    id: 7,
    title: "Q7: Customer Segmentation (New / Returning / Loyal)",
    question: "Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.",
    sql: `WITH customer_type AS (
    SELECT customer_id, previous_purchases,
           CASE 
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;`,
    description: "Classifies customer base by purchasing frequency into New (1), Returning (2-10), and Loyal (>10).",
    category: "Customer Lifecycle"
  },
  {
    id: 8,
    title: "Q8: Top 3 Products per Category",
    question: "What are the top 3 most purchased products within each category?",
    sql: `WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;`,
    description: "Window function analysis extracting category leaders across Accessories, Clothing, Footwear, Outerwear.",
    category: "Product Performance"
  },
  {
    id: 9,
    title: "Q9: Repeat Buyers Subscription Status",
    question: "Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?",
    sql: `SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;`,
    description: "Analyzes subscription adoption specifically among frequent buyers (>5 prior orders).",
    category: "Subscription ROI"
  },
  {
    id: 10,
    title: "Q10: Revenue Contribution by Age Group",
    question: "What is the revenue contribution of each age group?",
    sql: `WITH age_binned AS (
    SELECT 
        CASE 
            WHEN age <= 31 THEN 'Young Adult (18-31)'
            WHEN age BETWEEN 32 AND 44 THEN 'Adult (32-44)'
            WHEN age BETWEEN 45 AND 57 THEN 'Middle-Aged (45-57)'
            ELSE 'Senior (58+)'
        END AS age_group,
        purchase_amount
    FROM customer
)
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM age_binned
GROUP BY age_group
ORDER BY total_revenue DESC;`,
    description: "Demographic breakdown of total revenue across Young Adult, Adult, Middle-Aged, and Senior cohorts.",
    category: "Demographics"
  }
];
